#pragma once

// projects/qemu_virt_arm64/include/guest_config.hpp
//
// Static guest configuration for the QEMU virt AArch64 target.
//
// Phase 5 supports a single guest, identity-mapped through Stage 2.
// These constants feed the GuestDescriptor table defined in
// ../guest_config.cpp — components consume them only through
// nova::guest_table() (nova/abi/guest.hpp), never by including this header.
//
// Per-guest scalars (window size, vcpus, uart) now come from the
// embedded DTBs (tools/yml2dtb, switched by task.sh build --config);
// only the index-derived placement rules remain compile-time here.

#include "nova/abi/guest_layout.h"

#include <cstddef>
#include <cstdint>

namespace nova::qemu_virt {

// Guest IPA window, from the layout header shared with the demo guest
// linker script (demo/common/linker.ld.S). Every guest sees (and links
// against) the same window; only the backing PA slot differs.
// QEMU -device loader,file=<binary>,addr=<slot PA>,force-raw=on places
// each guest binary at its slot; Stage 2 maps the window onto it.
inline constexpr std::uint64_t kGuestIpaBase = NOVA_GUEST_IPA_BASE;
inline constexpr std::uint64_t kGuestIpaSize = NOVA_GUEST_IPA_SIZE;

// Guest PA windows pack from the IPA base: each guest starts where the
// previous window ended, rounded up to the Block alignment. Slot 0 is
// identity with the IPA window, and guests no larger than the alignment
// reproduce the former fixed-stride placement, so existing manifests'
// load_addr values stay valid. Mirrored by tools/yml2dtb's collision
// checks at build time.
[[nodiscard]] constexpr auto align_up_pa(std::uint64_t addr) noexcept -> std::uint64_t {
  return (addr + NOVA_GUEST_PA_ALIGN - 1) & ~static_cast<std::uint64_t>(NOVA_GUEST_PA_ALIGN - 1);
}

// EL1 entry PC. The demo's linker.ld places .text.start at IPA base.
inline constexpr std::uint64_t kGuestEntry = kGuestIpaBase;

// Per-guest DTB IPA and initial SP_EL1: the DTB reservation sits at the
// configured window top and the stack grows down from it. For the
// minimum window this equals the link-time __stack_top demo/common/
// linker.ld.S derives from the same macros.
[[nodiscard]] constexpr auto guest_dtb_ipa(std::uint64_t mem_size) noexcept -> std::uint64_t {
  return kGuestIpaBase + mem_size - NOVA_GUEST_DTB_SIZE;
}

// Builds the runtime guest table from the embedded per-guest DTBs
// (g_guest_dtbs, generated by yml2dtb). Must run once on the boot
// core before anything consumes nova::guest_table() — called at the
// top of novavisor_main(), ahead of RuntimeStart.
void init_guest_table() noexcept;

} // namespace nova::qemu_virt
