#pragma once

// projects/qemu_virt_arm64/include/guest_config.hpp
//
// Static guest configuration for the QEMU virt AArch64 target.
//
// Phase 5 supports a single guest, identity-mapped through Stage 2.
// These constants feed the GuestDescriptor table defined in
// ../guest_config.cpp — components consume them only through
// nova::guest_table() (nova/abi/guest.hpp), never by including this header.
//
// Per-guest scalars (window size, vcpus, uart) now come from the
// embedded DTBs (tools/yml2dtb, switched by task.sh build --config);
// only the index-derived placement rules remain compile-time here.

#include "nova/abi/guest_layout.h"

#include <cstddef>
#include <cstdint>

namespace nova::qemu_virt {

// Guest IPA window, from the layout header shared with the demo guest
// linker script (demo/common/linker.ld.S). Every guest sees (and links
// against) the same window; only the backing PA slot differs.
// QEMU -device loader,file=<binary>,addr=<slot PA>,force-raw=on places
// each guest binary at its slot; Stage 2 maps the window onto it.
inline constexpr std::uint64_t kGuestIpaBase = NOVA_GUEST_IPA_BASE;
inline constexpr std::uint64_t kGuestIpaSize = NOVA_GUEST_IPA_SIZE;

// PA slot for guest i. Slot 0 is identity with the IPA window, so the
// Phase 5/6 single-guest demos keep their manifests unchanged.
[[nodiscard]] constexpr auto guest_slot_pa(std::size_t index) noexcept -> std::uint64_t {
  return NOVA_GUEST_IPA_BASE + (index * NOVA_GUEST_PA_STRIDE);
}

// EL1 entry PC. The demo's linker.ld places .text.start at IPA base.
inline constexpr std::uint64_t kGuestEntry = kGuestIpaBase;

// Initial SP_EL1. Stack grows down from the guest DTB reservation at
// the linker-window top (guest_layout.h); demo/common/linker.ld.S
// derives its __stack_top from the same macros, matched at build time.
inline constexpr std::uint64_t kGuestStackTop = NOVA_GUEST_DTB_IPA;

// Builds the runtime guest table from the embedded per-guest DTBs
// (g_guest_dtbs, generated by yml2dtb). Must run once on the boot
// core before anything consumes nova::guest_table() — called at the
// top of novavisor_main(), ahead of RuntimeStart.
void init_guest_table() noexcept;

} // namespace nova::qemu_virt
