"""Demo use cases: catalog, build, launch, verification, and soak."""

from __future__ import annotations

import sys
import time
from pathlib import Path

from ..core import board, config, proc
from ..image import abi
from . import artifacts, cmake, expect, manifest, report, suite, surfaces, verify


def _launch(name: str) -> tuple[Path, dict, list[str]]:
    """Build a demo and its hypervisor, then compose the QEMU command."""
    _, demo_manifest = manifest.load_manifest(name)
    demo_build = artifacts.build_demos()
    payloads = artifacts.prepare_payload_manifest(name, demo_build, demo_manifest)
    guest_config = manifest.manifest_config(demo_manifest)
    elf = cmake.build(
        cmake.BuildSpec.of(
            preset=config.HV_PRESET,
            config_path=None if guest_config is None else config.REPO / guest_config,
            payloads_path=payloads,
        )
    )
    command = artifacts.build_qemu_cmd(elf, name, demo_build, demo_manifest)
    return demo_build, demo_manifest, command


def _debug(name: str) -> int:
    demo_build, demo_manifest, command = _launch(name)

    symbols_script = demo_build / "debug-symbols.gdb"
    symbols_script.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# Auto-generated by nova demo run {name} --debug"]
    for guest in demo_manifest.get("guests", []):
        stem = Path(guest["binary"]).stem
        guest_elf = demo_build / name / stem
        if not guest_elf.exists():
            guest_elf = (
                config.REPO / "external" / "cache" / "guests" / name / f"{stem}.elf"
            )
        if guest_elf.exists():
            offset = guest["load_addr"] - abi.GUEST_IPA_BASE
            option = f" -o {offset:#x}" if offset else ""
            lines.append(f"add-symbol-file {guest_elf}{option}")
    symbols_script.write_text("\n".join(lines) + "\n")

    print("==> Launching QEMU with GDB stub on :1234 (CPU halted).")
    print(f"==> Demo: {name}  guest symbols: {symbols_script}")
    print("==> Press Ctrl-A then x in QEMU to exit.")
    return proc.call(command + ["-s", "-S"])


def list_demos() -> int:
    demos = manifest.iter_demos()
    if not demos:
        print("(no demos)")
        return 0
    print(f"{'ID':>2}  {'NAME':30s}  {'PHASE':>5}  {'ENABLED':>7}  DESCRIPTION")
    for name, demo_manifest in demos:
        print(
            f"{manifest.demo_id(name):>2}  {name:30s}  "
            f"{demo_manifest.get('phase', '?'):>5}  "
            f"{str(demo_manifest.get('enabled', False)).lower():>7}  "
            f"{demo_manifest.get('description', '')}"
        )
    return 0


def build() -> int:
    artifacts.build_demos()
    return 0


def fetch(name: str | None, *, all_demos: bool = False) -> int:
    if all_demos:
        return suite.fetch_all()
    if name is None:
        raise ValueError("one demo or all_demos=True is required")
    script = config.DEMO_DIR / name / "fetch.sh"
    if not script.exists():
        print(f"[{suite.SCOPE}] {name}: no external images to fetch")
        return 0
    return proc.call(["bash", str(script)])


def run(name: str, *, debug: bool = False) -> int:
    if debug:
        return _debug(name)
    *_, command = _launch(name)
    # A run somebody is sitting in front of is a run being watched, so
    # it gets the surfaces that make it readable — the same ones a
    # scenario asks for when its steps do the watching. Without them
    # there is no machine for `nova workbench command` to drive, and
    # reproducing a CI failure by hand would need a second way to start.
    opened = surfaces.make_surfaces()
    command = board.attach_workbench(
        list(command),
        shm_path=opened.shm_path,
        qmp_path=opened.qmp_path,
        gdb_path=opened.gdb_path,
    )
    print(f"[{suite.SCOPE}] Press Ctrl-A x to exit QEMU.")
    try:
        return proc.call(command)
    finally:
        opened.release()


def verify_one(name: str, artifact_dir: Path | None = None) -> int:
    return suite.verify_one(name, report.ArtifactPaths.from_arg(artifact_dir))


def verify_all(artifact_dir: Path | None = None) -> int:
    return suite.verify_all(report.ArtifactPaths.from_arg(artifact_dir))


def soak(
    name: str,
    runs: int,
    *,
    summary: Path | None = None,
    artifact_dir: Path | None = None,
) -> int:
    _, demo_manifest = manifest.load_manifest(name)
    if not demo_manifest.get("enabled", False):
        print(f"[{suite.SCOPE}] SKIP {name} (manifest.enabled=false)")
        return 0

    if summary is not None:
        report.initialize_repeat_summary(summary)
    paths = report.ArtifactPaths.from_arg(artifact_dir)

    demo_build = artifacts.build_demos()
    snapshots = []
    scenarios = []
    for index, variant in enumerate(
        manifest.manifest_variants(demo_manifest),
        start=1,
    ):
        snapshot = (
            config.BUILD_ROOT
            / "demo-repeat"
            / name
            / f"variant-{index}"
            / "novavisor.elf"
        )
        snapshots.append(snapshot)
        scenarios.append(
            artifacts.scenario_for(
                name,
                demo_manifest,
                variant,
                demo_build=demo_build,
                elf_snapshot=snapshot,
            )
        )

    def report_attempt(attempt: expect.RepeatAttempt) -> None:
        print(
            f"[{suite.SCOPE}] repeat {attempt.number}/{runs}: "
            f"{attempt.status.upper()} ({attempt.elapsed_seconds:.1f}s)"
        )
        if attempt.error:
            print(f"[{suite.SCOPE}] repeat error: {attempt.error}", file=sys.stderr)
        if summary is not None:
            report.append_repeat_summary(summary, attempt)

    def verify_once(attempt_number: int) -> int:
        for variant_number, scenario in enumerate(scenarios, start=1):
            tail = (
                None
                if paths is None
                else paths.repeat_tail(attempt_number, variant_number)
            )
            result = verify.run_scenario(scenario, suite.sink(tail), scope=suite.SCOPE)
            if result != 0:
                return result
        return 0

    attempts = expect.run_repeated(
        runs,
        verify_once,
        clock=time.monotonic,
        on_attempt=report_attempt,
    )
    passed = sum(attempt.ok for attempt in attempts)
    total_seconds = sum(attempt.elapsed_seconds for attempt in attempts)
    print(
        f"[{suite.SCOPE}] repeat summary: {passed}/{len(attempts)} passed "
        f"({100.0 * passed / len(attempts):.1f}%), total={total_seconds:.1f}s"
    )
    report.append_github_summary(f"{name} recovery soak", attempts, summary)
    if passed != len(attempts) and paths is not None:
        report.collect_evidence(paths, name, demo_manifest, snapshots)
    return 0 if passed == len(attempts) else 1
