"""Demo commands: list, build, fetch, launch, verify, and soak the demo guests."""

from __future__ import annotations

import sys
import time
from pathlib import Path

from ..core import config, proc
from ..image import abi
from ..services import artifacts, cmake, expect, manifest, report, suite, verify


def _launch(name: str) -> tuple[Path, dict, list[str]]:
    """Shared run/debug prologue: build everything, compose the QEMU command."""
    _, demo_manifest = manifest.load_manifest(name)
    demo_build = artifacts.build_demos()
    payloads = artifacts.prepare_payload_manifest(name, demo_build, demo_manifest)
    guest_config = manifest.manifest_config(demo_manifest)
    elf = cmake.build(cmake.BuildSpec.of(
        preset=config.HV_PRESET,
        config_path=None if guest_config is None else config.REPO / guest_config,
        payloads_path=payloads,
    ))
    command = artifacts.build_qemu_cmd(elf, name, demo_build, demo_manifest)
    return demo_build, demo_manifest, command


def _debug(name: str) -> int:
    demo_build, demo_manifest, command = _launch(name)

    # A fixed path lets the debugger load symbols without prompting twice.
    symbols_script = demo_build / "debug-symbols.gdb"
    symbols_script.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# Auto-generated by nova demo run {name} --debug"]
    for guest in demo_manifest.get("guests", []):
        # Guest ELF sits next to its .bin with the extension stripped
        # (add_demo_guest(<name> ...) produces <name> and <name>.bin);
        # external images cache theirs as <stem>.elf next to the .bin.
        stem = Path(guest["binary"]).stem
        guest_elf = demo_build / name / stem
        if not guest_elf.exists():
            guest_elf = config.REPO / "external" / "cache" / "guests" / name / f"{stem}.elf"
        if guest_elf.exists():
            # Every guest links at the shared IPA window base but is
            # loaded at its PA slot — shift the symbols by the slot
            # offset so multi-VM demos resolve at the right addresses.
            offset = guest["load_addr"] - abi.GUEST_IPA_BASE
            opt = f" -o {offset:#x}" if offset else ""
            lines.append(f"add-symbol-file {guest_elf}{opt}")
    symbols_script.write_text("\n".join(lines) + "\n")

    print("==> Launching QEMU with GDB stub on :1234 (CPU halted).")
    print(f"==> Demo: {name}  guest symbols: {symbols_script}")
    print("==> Press Ctrl-A then x in QEMU to exit.")
    return proc.call(command + ["-s", "-S"])


def _list(_args) -> int:
    demos = manifest.iter_demos()
    if not demos:
        print("(no demos)")
        return 0
    print(f"{'ID':>2}  {'NAME':30s}  {'PHASE':>5}  {'ENABLED':>7}  DESCRIPTION")
    for name, mf in demos:
        print(f"{manifest.demo_id(name):>2}  {name:30s}  {mf.get('phase', '?'):>5}  "
              f"{str(mf.get('enabled', False)).lower():>7}  "
              f"{mf.get('description', '')}")
    return 0


def _build(_args) -> int:
    artifacts.build_demos()
    return 0


def _fetch(args) -> int:
    if args.all:
        return suite.fetch_all()
    if args.name is None:
        sys.exit(f"{suite.SCOPE}: fetch requires a demo id/name or --all")
    script = config.DEMO_DIR / args.name / "fetch.sh"
    if not script.exists():
        # Same contract as --all: nothing to fetch is not a failure, so a
        # caller need not know which demos ship external images.
        print(f"[{suite.SCOPE}] {args.name}: no external images to fetch")
        return 0
    return proc.call(["bash", str(script)])


def _run(args) -> int:
    if args.debug:
        return _debug(args.name)
    *_, command = _launch(args.name)
    print(f"[{suite.SCOPE}] Press Ctrl-A x to exit QEMU.")
    return proc.call(command)


def _verify(args) -> int:
    return suite.verify_one(args.name, report.ArtifactPaths.from_arg(args.artifacts))


def _verify_all(args) -> int:
    return suite.verify_all(report.ArtifactPaths.from_arg(args.artifacts))


def _soak(args) -> int:
    _, demo_manifest = manifest.load_manifest(args.name)
    if not demo_manifest.get("enabled", False):
        print(f"[{suite.SCOPE}] SKIP {args.name} (manifest.enabled=false)")
        return 0

    summary_path = Path(args.summary) if args.summary else None
    if summary_path is not None:
        report.initialize_repeat_summary(summary_path)
    paths = report.ArtifactPaths.from_arg(args.artifacts)

    demo_build = artifacts.build_demos()
    snapshots = []
    scenarios = []
    for index, variant in enumerate(manifest.manifest_variants(demo_manifest), start=1):
        snapshot = (config.BUILD_ROOT / "demo-repeat" / args.name
                    / f"variant-{index}" / "novavisor.elf")
        snapshots.append(snapshot)
        scenarios.append(artifacts.scenario_for(
            args.name,
            demo_manifest,
            variant,
            demo_build=demo_build,
            elf_snapshot=snapshot,
        ))

    def report_attempt(attempt: expect.RepeatAttempt) -> None:
        print(f"[{suite.SCOPE}] repeat {attempt.number}/{args.runs}: "
              f"{attempt.status.upper()} ({attempt.elapsed_seconds:.1f}s)")
        if attempt.error:
            print(f"[{suite.SCOPE}] repeat error: {attempt.error}", file=sys.stderr)
        if summary_path is not None:
            report.append_repeat_summary(summary_path, attempt)

    def verify_once(attempt_number: int) -> int:
        for variant_number, scenario in enumerate(scenarios, start=1):
            tail = (
                None if paths is None
                else paths.repeat_tail(attempt_number, variant_number)
            )
            rc = verify.run_scenario(scenario, suite.sink(tail), scope=suite.SCOPE)
            if rc != 0:
                return rc
        return 0

    attempts = expect.run_repeated(
        args.runs,
        verify_once,
        clock=time.monotonic,
        on_attempt=report_attempt,
    )
    passed = sum(attempt.ok for attempt in attempts)
    total_seconds = sum(attempt.elapsed_seconds for attempt in attempts)
    print(f"[{suite.SCOPE}] repeat summary: {passed}/{len(attempts)} passed "
          f"({100.0 * passed / len(attempts):.1f}%), total={total_seconds:.1f}s")
    report.append_github_summary(f"{args.name} recovery soak", attempts, summary_path)
    if passed != len(attempts) and paths is not None:
        report.collect_evidence(paths, args.name, demo_manifest, snapshots)
    return 0 if passed == len(attempts) else 1


def register(subcommands) -> None:
    parser = subcommands.add_parser("demo", help="build and verify demo guests")
    operations = parser.add_subparsers(dest="demo_command", required=True)

    operations.add_parser("list", help="list demos").set_defaults(handler=_list)
    operations.add_parser("build", help="build in-tree guests").set_defaults(
        handler=_build
    )
    demo_arg = {
        "metavar": "id|name",
        "type": manifest.resolve_demo,
        "help": "demo ID or directory name",
    }
    fetch = operations.add_parser("fetch", help="populate external image cache")
    fetch.add_argument("name", nargs="?", **demo_arg)
    fetch.add_argument("--all", action="store_true")
    fetch.set_defaults(handler=_fetch)

    run = operations.add_parser("run", help="launch interactively")
    run.add_argument("name", **demo_arg)
    run.add_argument("--debug", action="store_true")
    run.set_defaults(handler=_run)

    single = operations.add_parser("verify", help="check expected output")
    single.add_argument("name", **demo_arg)
    single.add_argument("--artifacts", metavar="DIR")
    single.set_defaults(handler=_verify)

    soak = operations.add_parser("soak", help="repeat one verification")
    soak.add_argument("name", **demo_arg)
    soak.add_argument(
        "--runs",
        type=int,
        required=True,
        choices=range(1, 101),
        metavar="N",
    )
    soak.add_argument("--summary", metavar="CSV")
    soak.add_argument("--artifacts", metavar="DIR")
    soak.set_defaults(handler=_soak)

    every = operations.add_parser("verify-all", help="verify enabled demos")
    every.add_argument("--artifacts", metavar="DIR")
    every.set_defaults(handler=_verify_all)
